name: TEST1 
on: 
  push:
    paths:
      - README.md 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: asession
      uses: mxschmitt/action-tmate@v3
